### ISSUE TITLE
Why CMake 3.8 + C++17 as pre-requisite ?

### ISSUE THREAD

**Issue by ebachard** [kjetand/imvlc#12]
Hi,

First, thanks a lot for sharing your code. I randomly found the existence of imvlc, but what you do is extremely interesting, and has a big potential !

The issue is : since I was able to build using c++14 + CMake 3.5, why do you ask for CMake3.8 and c++17 as pre-requisite ?

I was able to build imvlc and test example-hello-world using two videos as requested. got g++-5.4 only, and since I'm not sure g++-5.4 is c++17 compliant, I turned all the C17 into C14 and I was able to build everything as expected (below the diff, just FYI). My machine is old (mbp 6,2 Intel i7+ 8GB RAM + Linux mint 18.3), but the load is around 40% in my test. This is extremely acceptable for a test, and is showing what libvlc can do, very efficiently (this is even impressive !)
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index fce0afa..bcb1ca3 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -1,4 +1,7 @@
-cmake_minimum_required(VERSION 3.8)
+cmake_minimum_required(VERSION 3.5)
+
+set (CMAKE_CXX_STANDARD 14)
+set (CMAKE_CXX_STANDARD_REQUIRED ON)
 
 set(CMAKE_DISABLE_IN_SOURCE_BUILD ON)
 set(CMAKE_DISABLE_SOURCE_CHANGES  ON)
diff --git a/examples/CMakeLists.txt b/examples/CMakeLists.txt
index 6123be8..d463a69 100644
--- a/examples/CMakeLists.txt
+++ b/examples/CMakeLists.txt
@@ -1,6 +1,6 @@
 project(examples)
 
-set(CMAKE_CXX_STANDARD 17)
+set(CMAKE_CXX_STANDARD 14)
 set(CXX_STANDARD_REQUIRED ON)
 
 set(HELLO_WORLD_DEMO "${PROJECT_NAME}-hello-world")
diff --git a/external/imgui-sfml b/external/imgui-sfml
--- a/external/imgui-sfml
+++ b/external/imgui-sfml
@@ -1 +1 @@
-Subproject commit 65e343c1339cfd24e3752bceeb955c3b58449fd0
+Subproject commit 65e343c1339cfd24e3752bceeb955c3b58449fd0-dirty
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index 4b54bae..f163e7d 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -1,6 +1,6 @@
 project(imvlc VERSION 1.0)
 
-set(CMAKE_CXX_STANDARD 17)
+set(CMAKE_CXX_STANDARD 14)
 set(CXX_STANDARD_REQUIRED ON)
 
 set(CMAKE_POSITION_INDEPENDENT_CODE ON)
YYYYY@XXXXXX ~/Devel/current/imvlc $ 

```
FYI, I'm working at something a bit different (see my miniDart repo - sorry french description-), and I'm using SDL2 + ImGui + OpenCV + OpenGL + ffmpeg + NativeFileDialog, but not libvlc. I'm a simple developer (not a pro), but I really appreciate your idea and will certainly continue to keep an eye on imvlc to provide feedack if I can, and continue to learn a lot, e.g. a far better C++ coding style than mine :-)

**Comment by kjetand** [comment]
Hi. Thanks for the kind words! I'm excited to hear that you like the idea behind the framework. Hopefully some day I will make a first "release-ready" version, but for now I'm in early development/experiment/idea mode :)

The reason behind CMake 3.8 is C++17. And yes, perhaps the code is not C++17 yet, but I'm planning to use some C++17 features in the future (e.g. in previous commit I used "if constexpr"). However, I could of course downgrade the version until I get a compiler error some day.

I don't know french, but your project looks interesting. Will take a look!

Hope to get more feedback in the future.

**Comment by ebachard** [comment]
You're welcome :-) 

FYI, there is now an english presentation, explaining miniDart project.

**Comment by kjetand** [comment]
Changed required version to C++14 and CMake 3.5. May change in the future, but for now its probably better.
